import echarts from 'echarts/lib/echarts';
import 'echarts/lib/chart/line';
import 'echarts/lib/chart/pie';
import 'echarts/lib/chart/bar';
import 'echarts/lib/chart/radar';
import 'echarts/lib/chart/gauge';
import 'echarts/lib/component/legend';
import 'echarts/lib/component/markPoint';
export { ECharts, EChartOption } from 'echarts';
export default echarts;
